services:
  ubuntu:
    image: ubuntu:latest
    pull_policy: missing
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ubuntu-demo-volume:/data/
    ## флаг -i (для поддержки pipeline | и отмены остановки контейнера после запуска, поддержка открытого интерактивного STDIN)
    stdin_open: true
    ## флаг -t (для скрытия паролей, поддержка интерактивного STDIN и STDOUT)
    tty: true

volumes:
  ubuntu-demo-volume:
    ## если используем существующий том Docker
    # external: true